version: '2'
services:
  lmf-webshop-frontend:
    build:
      context: ./WebshopFrontend/particulier
      dockerfile: Dockerfile
    image: docentm:5000/lmf-webshop-frontend:${BUILD_BUILDNUMBER}

  lmf-webshop.api:
    build:
      context: ./WebshopAPI/src/Webshop.API
      dockerfile: Dockerfile
      args: 
        SOURCE: ./bin/publish
    image: docentm:5000/lmf-webshop.api:${BUILD_BUILDNUMBER}
    
  lmf-webshop.listener:
    build:
      context: ./WebshopAPI/src/Webshop.Listener
      dockerfile: Dockerfile
      args: 
        SOURCE: ./bin/publish
    image: docentm:5000/lmf-webshop.listener:${BUILD_BUILDNUMBER}
    
  lmf-webshopbeheer:
    build:
      context: ./WebshopBeheer/src/WebshopBeheer
      dockerfile: Dockerfile
      args: 
        SOURCE: ./bin/publish
    image: docentm:5000/lmf-webshopbeheer:${BUILD_BUILDNUMBER}

  lmf-bestelservice:
    build:
      context: ./BestelService/src/BestelService
      dockerfile: Dockerfile
      args: 
        SOURCE: ./bin/publish
    image: docentm:5000/lmf-bestelservice:${BUILD_BUILDNUMBER}
    
  lmf-factuurservice:
    build:
      context: ./FactuurService/src/FactuurService
      dockerfile: Dockerfile
      args: 
        SOURCE: ./bin/publish
    image: docentm:5000/lmf-factuurservice:${BUILD_BUILDNUMBER}