version: '2'

services:
    lmf-img-storage:
        container_name: lmf-img-storage
        image: phusion/baseimage:latest
        networks:
            - kantilever
        volumes: 
            - /img
        ports:
            - 7559:3306

    lmf-bestelservice.database:
        image: mysql:latest
        hostname: "lmf-bestelservice.database"
        environment:
            - MYSQL_ROOT_PASSWORD=my-secret-pw
            - RABBITMQ_HOSTNAME=rabbitmq
            - RABBITMQ_USERNAME=rabbitmq
            - RABBITMQ_PASSWORD=rabbitmq
            - MYSQL_CONNECTION=server=lmf-bestelservice.database;userid=root;pwd=my-secret-pw;port=3306;database=BestellingenKantilever;sslmode=none;      
        container_name: lmf-bestelservice.database
        networks: 
            - kantilever

    lmf-factuurservice.database:
        image: mysql:latest
        hostname: "lmf-factuurservice.database"
        environment:
            - MYSQL_ROOT_PASSWORD=my-secret-pw
            - RABBITMQ_HOSTNAME=rabbitmq
            - RABBITMQ_USERNAME=rabbitmq
            - RABBITMQ_PASSWORD=rabbitmq
            - MYSQL_CONNECTION=server=lmf-factuurservice.database;userid=root;pwd=my-secret-pw;port=3306;database=FacturenKantilever;sslmode=none;      
        container_name: lmf-factuurservice.database
        networks: 
            - kantilever

    lmf-webfrontend.api.database:
        image: mysql:latest
        hostname: "lmf-webfrontend.api.database"
        environment:
            - MYSQL_ROOT_PASSWORD=my-secret-pw
            - RABBITMQ_HOSTNAME=rabbitmq
            - RABBITMQ_USERNAME=rabbitmq
            - RABBITMQ_PASSWORD=rabbitmq
            - MYSQL_CONNECTION=server=lmf-webfrontend.api.database;userid=root;pwd=my-secret-pw;port=3306;database=ArtikelenKantilever;sslmode=none;      
        container_name: lmf-webfrontend.api.database
        networks: 
            - kantilever
        ports:
            - 4567:3306

    lmf-webshop-frontend:
        container_name: lmf-webshop-frontend
        image: docentm:5000/lmf-webshop-frontend:${BUILD_BUILDNUMBER}
        networks: 
            - kantilever
        ports:
            - 7000:80
        volumes_from: 
            - lmf-img-storage

    lmf-webshopbeheer:
        container_name: lmf-webshopbeheer
        image: docentm:5000/lmf-webshopbeheer:${BUILD_BUILDNUMBER}
        environment:
            - RABBITMQ_HOSTNAME=rabbitmq
            - RABBITMQ_USERNAME=rabbitmq
            - RABBITMQ_PASSWORD=rabbitmq
        networks: 
            - kantilever
        ports: 
            - 8081:5000

    lmf-webshop.api:
        container_name: lmf-webshop.api
        image: docentm:5000/lmf-webshop.api:${BUILD_BUILDNUMBER}
        environment:
            - RABBITMQ_HOSTNAME=rabbitmq
            - RABBITMQ_USERNAME=rabbitmq
            - RABBITMQ_PASSWORD=rabbitmq
            - MYSQL_CONNECTION=server=lmf-webfrontend.api.database;userid=root;pwd=my-secret-pw;port=3306;database=ArtikelenKantilever;sslmode=none;
        networks: 
            - kantilever
        ports: 
            - 8090:5000

    lmf-webshop.listener:
        container_name: lmf-webshop.listener
        image: docentm:5000/lmf-webshop.listener:${BUILD_BUILDNUMBER}
        environment:
            - RABBITMQ_HOSTNAME=rabbitmq
            - RABBITMQ_USERNAME=rabbitmq
            - RABBITMQ_PASSWORD=rabbitmq
            - IMG_ROOT=/img
        networks: 
            - kantilever
        volumes_from: 
            - lmf-img-storage

    lmf-bestelservice:
        container_name: lmf-bestelservice
        image: docentm:5000/lmf-bestelservice:${BUILD_BUILDNUMBER}
        environment:
            - RABBITMQ_HOSTNAME=rabbitmq
            - RABBITMQ_USERNAME=rabbitmq
            - RABBITMQ_PASSWORD=rabbitmq
            - MYSQL_CONNECTION=server=lmf-bestelservice.database;userid=root;pwd=my-secret-pw;port=3306;database=BestellingenKantilever;sslmode=none;
        networks: 
            - kantilever
    
    lmf-factuurservice:
        container_name: lmf-factuurservice
        image: docentm:5000/lmf-factuurservice:${BUILD_BUILDNUMBER}
        environment:
            - RABBITMQ_HOSTNAME=rabbitmq
            - RABBITMQ_USERNAME=rabbitmq
            - RABBITMQ_PASSWORD=rabbitmq
            - MYSQL_CONNECTION=server=lmf-factuurservice.database;userid=root;pwd=my-secret-pw;port=3306;database=FacturenKantilever;sslmode=none;
        networks: 
            - kantilever

    rabbitmq:
        image: rabbitmq:3-management
        hostname: "rabbitmq"
        environment:
            - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
            - RABBITMQ_DEFAULT_USER=rabbitmq
            - RABBITMQ_DEFAULT_PASS=rabbitmq
            - RABBITMQ_DEFAULT_VHOST=/         
        container_name: rabbitmq
        ports:
            - 15672:15672
        networks: 
            - kantilever           
            
networks: 
    kantilever:
        driver: bridge 
