version: '2'
services:
  lmf-webshop-frontend:
    build:
      context: ./WebshopFrontend/particulier
      dockerfile: Dockerfile     

  lmf-webshopbeheer:
    build:
      context: ./WebshopBeheer/src/WebshopBeheer
      dockerfile: Dockerfile
      args: 
        SOURCE: ./bin/publish