version: '2'
services:
  lmf-webshop-frontend:
    build:
      context: ./WebshopFrontend/particulier
      dockerfile: Dockerfile
      image: docentm:5000/lmf-webshop-frontend

  lmf-webshopbeheer:
    build:
      context: ./WebshopBeheer/src/WebshopBeheer
      dockerfile: Dockerfile
      args: 
        SOURCE: ./bin/publish
      image: docentm:5000/lmf-webshopbeheer