version: '2'
services: 
    lmf-webshop-frontend:
        container_name: lmf-webshop-frontend
        image: docentm:5000/lmf-webshop-frontend:${BUILD_BUILDNUMBER}
        networks: 
            - kantilever
        ports:
            - 7000:80

    lmf-webshopbeheer:
        container_name: lmf-webshopbeheer
        image: docentm:5000/lmf-webshopbeheer:${BUILD_BUILDNUMBER}
        environment:
            - RABBITMQ_HOSTNAME=rabbitmq-client
            - RABBITMQ_USERNAME=rabbitmq
            - RABBITMQ_PASSWORD=rabbitmq
        networks: 
            - kantilever
        ports: 
            - 8081:5000

    lmf-webshop.api:
        container_name: lmf-webshop.api
        image: docentm:5000/lmf-webshop.api:${BUILD_BUILDNUMBER}
        environment:
            - RABBITMQ_HOSTNAME=rabbitmq-client
            - RABBITMQ_USERNAME=rabbitmq
            - RABBITMQ_PASSWORD=rabbitmq
        networks: 
            - kantilever
        ports: 
            - 8090:5000

    lmf-webshop.listener:
        container_name: lmf-webshop.listener
        image: docentm:5000/lmf-webshop.listener:${BUILD_BUILDNUMBER}
        environment:
            - RABBITMQ_HOSTNAME=rabbitmq-client
            - RABBITMQ_USERNAME=rabbitmq
            - RABBITMQ_PASSWORD=rabbitmq
        networks: 
            - kantilever

    lmf-bestelservice:
        container_name: lmf-bestelservice
        image: docentm:5000/lmf-bestelservice:${BUILD_BUILDNUMBER}
        environment:
            - RABBITMQ_HOSTNAME=rabbitmq-client
            - RABBITMQ_USERNAME=rabbitmq
            - RABBITMQ_PASSWORD=rabbitmq
        networks: 
            - kantilever
    
    lmf-factuurservice:
        container_name: lmf-factuurservice
        image: docentm:5000/lmf-factuurservice:${BUILD_BUILDNUMBER}
        environment:
            - RABBITMQ_HOSTNAME=rabbitmq-client
            - RABBITMQ_USERNAME=rabbitmq
            - RABBITMQ_PASSWORD=rabbitmq
        networks: 
            - kantilever

    rabbitmq:
        image: rabbitmq:3-management
        hostname: "rabbitmq-client"
        environment:
            - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
            - RABBITMQ_DEFAULT_USER=rabbitmq
            - RABBITMQ_DEFAULT_PASS=rabbitmq
            - RABBITMQ_DEFAULT_VHOST=/         
        container_name: rabbitmq
        ports:
            - 15672:15672
        networks: 
            - kantilever

networks: 
    kantilever:
        driver: bridge