version: '2'

services:
    particulier:
        build: 
            context: .
            dockerfile: ./.docker/development.dockerfile
        ports:
            - "69:4200"
            - "49153:49153"
        volumes:
            - .:/usr/src/app
        command: npm start